//! Installed applications — the data an `@` mode row is made of, and the pure
//! rules that turn a raw platform listing into a usable list. The scanning
//! itself (COM on Windows, Spotlight on macOS) lives in `launchtype-services`.
//!
//! Two things are worth doing here rather than in the scanner. A scanner can
//! read the same app twice — macOS asks Spotlight *and* walks the applications
//! folders — and the names come back in whatever case and whatever language the
//! machine chose, while a launcher row has to be folded to sort. Both are pure,
//! so both are tested.

/// One launchable application.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct App {
    /// Display name, spelled the way the OS spells it. Matching folds case
    /// itself, so there is nothing to gain by flattening it here.
    pub name: String,
    pub target: AppTarget,
}

/// How to start an app. Not a path in the Windows case: half of what the
/// Applications folder lists (Store apps, and the "Microsoft.AutoGenerated"
/// control-panel entries) has no executable to spawn, only an identity the
/// shell knows how to activate.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum AppTarget {
    /// A Windows Application User Model ID, as `shell:AppsFolder` reports it:
    /// `Microsoft.WindowsCalculator_8wekyb3d8bbwe!App` for a packaged app,
    /// `{GUID}\Vendor\App.exe` for a Start Menu shortcut.
    AppUserModelId(String),
    /// Something the OS opener can start on its own: a `.app` bundle on macOS,
    /// a `.lnk` shortcut on Windows.
    Path(String),
}

impl AppTarget {
    /// The string form, for logging and for the dedupe key.
    pub fn as_str(&self) -> &str {
        match self {
            AppTarget::AppUserModelId(id) => id,
            AppTarget::Path(path) => path,
        }
    }
}

/// The display name for a launchable file: the file name without its
/// extension. Used where the scanner has a path and no name of its
/// own — the macOS bundle walk today, a Start Menu shortcut walk if one is ever
/// needed. (Windows has no use for it: the shell hands over the display name
/// alongside the target.)
///
/// Any extension is stripped, not just `.app`: `foo.exe` reads worse than
/// `foo`, and nothing is named for its extension.
pub fn display_name(path: &str) -> Option<String> {
    let file_name = path
        .trim_end_matches(['/', '\\'])
        .rsplit(['/', '\\'])
        .next()
        .filter(|name| !name.is_empty())?;
    let stem = match file_name.rsplit_once('.') {
        // A leading dot is a hidden file, not an extension: ".app" is not an
        // app called "" and must not become an empty row.
        Some((stem, _)) if !stem.is_empty() => stem,
        _ => file_name,
    };
    let name = stem.trim();
    (!name.is_empty()).then(|| name.to_string())
}

/// Normalise a raw scan into the list the mode shows: names trimmed, blanks
/// dropped, duplicates collapsed, sorted by name.
///
/// Duplicates are decided by target, not by name. Plenty of unrelated programs
/// ship a "Documentation" or an "Uninstall" entry, and collapsing those by name
/// would hide all but one of them; the same app found twice, on the other hand,
/// is the same target twice. Where a target does repeat, the first name wins,
/// which puts the scanner in charge of precedence by the order it returns.
///
/// Sorting is by the [`crate::i18n::fold`]ed name, not the raw one: this list
/// comes from the OS in the OS's language, and comparing bytes would file every
/// accented name — "Álbumes compartidos", "Administración de impresión" — after
/// the whole ASCII alphabet instead of next to its neighbours, and every
/// capitalised name ahead of every lowercase one.
pub fn normalize(apps: Vec<App>) -> Vec<App> {
    let mut seen: std::collections::HashSet<AppTarget> = std::collections::HashSet::new();
    let mut kept: Vec<App> = Vec::with_capacity(apps.len());
    for app in apps {
        let name = app.name.trim().to_string();
        if name.is_empty() || app.target.as_str().trim().is_empty() {
            continue;
        }
        if !seen.insert(app.target.clone()) {
            continue;
        }
        kept.push(App { name, target: app.target });
    }
    kept.sort_by(|a, b| {
        crate::i18n::fold(&a.name)
            .cmp(&crate::i18n::fold(&b.name))
            .then_with(|| a.name.cmp(&b.name))
            .then_with(|| a.target.cmp(&b.target))
    });
    kept
}

/// Drop the Steam games, which have a mode of their own.
///
/// Windows puts a Start Menu shortcut next to every installed game, so the
/// Applications folder hands back the whole library — 78 of 433 rows on the
/// machine this was written against — each one launching through the same
/// `steam://` URL `,` mode uses. Games belong to `,`; `@` is for everything
/// else, and reading a library out twice helps nobody.
///
/// The test is the URL scheme rather than a comparison against Steam mode's
/// list, so a game is `,` mode's business whether or not that mode is looking
/// at the library folder it happens to sit in.
pub fn without_steam(apps: Vec<App>) -> Vec<App> {
    apps.into_iter().filter(|app| !app.target.as_str().starts_with("steam://")).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn aumid(name: &str, id: &str) -> App {
        App { name: name.to_string(), target: AppTarget::AppUserModelId(id.to_string()) }
    }

    fn path(name: &str, path: &str) -> App {
        App { name: name.to_string(), target: AppTarget::Path(path.to_string()) }
    }

    #[test]
    fn display_names_drop_the_folder_and_the_extension() {
        assert_eq!(display_name("/Applications/Google Chrome.app").unwrap(), "Google Chrome");
        assert_eq!(display_name("/Applications/Utilities/Terminal.app/").unwrap(), "Terminal");
        let start_menu = r"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\7-Zip";
        assert_eq!(
            display_name(&format!(r"{start_menu}\7-Zip File Manager.lnk")).unwrap(),
            "7-Zip File Manager"
        );
        // A dotted name keeps everything but the last segment.
        assert_eq!(display_name("/Applications/Node.js 20.app").unwrap(), "Node.js 20");
    }

    #[test]
    fn nameless_paths_yield_nothing() {
        assert_eq!(display_name(""), None);
        assert_eq!(display_name("/"), None);
        assert_eq!(display_name("///"), None);
        // A leading dot is a hidden file, not an empty stem: ".app" is not an
        // application called "", and must not become a blank row.
        assert_eq!(display_name("/Applications/.app").unwrap(), ".app");
    }

    #[test]
    fn normalize_trims_sorts_and_drops_blanks() {
        let apps = normalize(vec![
            aumid("Notepad", "{GUID}\\notepad.exe"),
            aumid("Calculator", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"),
            aumid("   ", "Blank.Name"),
            aumid("Nowhere", "   "),
        ]);
        let names: Vec<&str> = apps.iter().map(|a| a.name.as_str()).collect();
        assert_eq!(names, ["Calculator", "Notepad"]);
    }

    /// The same app reached two ways is one row; two different apps that happen
    /// to share a name (every installer ships an "Uninstall") are still two.
    #[test]
    fn duplicates_are_decided_by_target_not_by_name() {
        let apps = normalize(vec![
            aumid("Firefox", "{GUID}\\Mozilla Firefox\\firefox.exe"),
            aumid("Mozilla Firefox", "{GUID}\\Mozilla Firefox\\firefox.exe"),
            path("Uninstall", r"C:\Start Menu\7-Zip\Uninstall.lnk"),
            path("Uninstall", r"C:\Start Menu\Vim\Uninstall.lnk"),
        ]);
        assert_eq!(apps.len(), 3);
        // First name wins for a repeated target.
        assert_eq!(apps[0].name, "Firefox");
        assert_eq!(apps[1].name, "Uninstall");
        assert_eq!(apps[2].name, "Uninstall");
        assert_ne!(apps[1].target, apps[2].target);
    }

    /// A localised Windows names half its Start Menu in the user's language,
    /// and comparing bytes would file every accented name after "z".
    #[test]
    fn accented_names_sort_next_to_their_neighbours() {
        let apps = normalize(vec![
            aumid("Zoom", "z"),
            aumid("Álbumes compartidos", "al"),
            aumid("Administración de equipos", "ad"),
            aumid("Bloc de notas", "b"),
        ]);
        let names: Vec<&str> = apps.iter().map(|a| a.name.as_str()).collect();
        assert_eq!(
            names,
            ["Administración de equipos", "Álbumes compartidos", "Bloc de notas", "Zoom"]
        );
    }

    /// The Start Menu carries a shortcut for every installed Steam game; those
    /// rows belong to `,` mode, and only those.
    #[test]
    fn steam_games_are_left_to_steam_mode() {
        let apps = normalize(vec![
            aumid("Portal 2", "steam://rungameid/620"),
            aumid("Team Fortress 2", "steam://rungameid/440"),
            aumid("Firefox", "{GUID}\\Mozilla Firefox\\firefox.exe"),
            // Steam itself is a program, not a game: it stays.
            aumid("Steam", "{GUID}\\Steam\\steam.exe"),
        ]);
        let kept = without_steam(apps);
        let names: Vec<&str> = kept.iter().map(|a| a.name.as_str()).collect();
        assert_eq!(names, ["Firefox", "Steam"]);
    }

    /// Rows are read out one after another, so equal names must not shuffle
    /// between scans; the target breaks the tie.
    #[test]
    fn equal_names_are_ordered_deterministically() {
        let first =
            normalize(vec![path("Help", "/b.lnk"), path("Help", "/a.lnk"), path("Help", "/c.lnk")]);
        let second =
            normalize(vec![path("Help", "/c.lnk"), path("Help", "/a.lnk"), path("Help", "/b.lnk")]);
        assert_eq!(first, second);
        assert_eq!(first[0].target, AppTarget::Path("/a.lnk".to_string()));
    }
}
