name: Release to GitHub

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: New Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-ci.txt

      - name: Make pyinstaller binary and copy sounds
        run: |
          pyinstaller ./main.spec
          xcopy sounds dist\launchtype\sounds /E /H /C /I
          xcopy locale dist\launchtype\locale /E /H /C /I

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          path: ./dist/launchtype
          filename: "launchtype ${{ github.ref }}.zip"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "launchtype ${{ github.ref }}.zip"
          tag_name: ${{ github.ref }}
          body: |
            This is a new release of LaunchType. For the user manual see https://www.oriolgomez.com/software/
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
